os: linux
dist: focal
services:
  - docker

# Because metatool checks for certain commits
git:
  depth: false

# 0-number of builds from "./metatool test"
env:
- TEST_BUILD=0
- TEST_BUILD=1
- TEST_BUILD=2
- TEST_BUILD=3
- TEST_BUILD=4

script:
  - echo $TEST_BUILD | ./metatool test

notifications:
  irc:
    channels:
      - "chat.freenode.net#albertlauncher"
    on_success: change
    on_failure: change
    template:
      - "%{repository_name#%{build_number} (%{commit}) : %{message}\n\n%{build_url}"
