language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc

before_install:
    - sudo apt-get install -qq cmake qtbase5-dev libqt5x11extras5-dev libqt5svg5-dev libmuparser-dev
 
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  
script:
  - make
  # Test installation process
  - make DESTDIR=appdir install ; find appdir/
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - find appdir/usr/lib/albert/ -name '*.so*' -exec mv {} ./appdir/usr/lib \;
  - sudo cp ./appdir/usr/lib/* /usr/lib/
  - rm -rf appdir/usr/lib/albert
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./Albert*.AppImage https://transfer.sh/Albert-git.$(git rev-parse --short HEAD)-x86_64.AppImage

notifications:
  irc:
    channels:
      - "chat.freenode.net#albertlauncher"
    on_success: never # default: always
    on_failure: always # default: always
