language: cpp
sudo: required
dist: trusty
compiler:
  - clang
  - gcc

install:
  - sudo add-apt-repository ppa:beineri/opt-qt551-trusty -y  # Qt-5.5
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake qt55base qt55x11extras qt55svg libmuparser-dev

script:
  - source /opt/qt55/bin/qt55-env.sh
  - cmake . -DCMAKE_BUILD_TYPE=Debug
  - make
  - sudo make install

notifications:
  irc:
    channels:
      - "chat.freenode.net#albertlauncher"
    on_success: always # default: always
    on_failure: always # default: always
